apiVersion: v1
kind: Secret
metadata:
    name: build-server-git-credentials
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:V7hIbuclB4M1Jqd04vf0IFnA6WDH6er4GxAOOp82UfET6WKXbZ6iDf9l74odhvWTGqCqRLCqpPV9adEPBiQEZg0o/U+RrinEvBkGprxrTMduMooFaDg+Z8OU5VAj,iv:bRlVqwTZtKQtqRj4HLg0C5uBpP65tPRqq7mRwqoNVoY=,tag:Y4turQThmQdksLhI77OY6Q==,type:str]
    username: ENC[AES256_GCM,data:Ut4Xzo73KxkddskBsU6zgQ==,iv:POVnTsLPus8z2PzIyZ1QeM9gcA+IrODyIIICMq9ysh0=,tag:O8ORREFNSaRcP6hBLhzAgQ==,type:str]
    email: ENC[AES256_GCM,data:sBxTCdphi32tO4eaNUnOoo9OxNp4lRBopprXzAKxC+Ivt6PwgZlld98=,iv:rMCINn4G/DXPIasxf15mFk3QkWz+RW8KgUvODilPvkU=,tag:gYNPBVhpCJ9JbZz9Z/0/FA==,type:str]
sops:
    age:
        - recipient: age10p7f8sn3v2r0973s8q4664sgxh4hpt8c0tp3w83w8m0zu5rkfccqge8atx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGcE5IL0NPY21XMG9XVDlD
            SWVoaUhYaStnSnRRelpVY1dqdVdJWU9OYlh3CjZIcklOTmFSMWNQVzhwZlRxV3hq
            NmNBTlZqMXBqNzBmTTR3aGg2Sm00ZWcKLS0tIFZYUXlvYUdCcnB4dHhpVWkrVCtk
            eXVuSE1welFKSURqNE5SckxrL0hLR2cKQtML3Z4x2ATvAbmqD86HyS0tgbACmYmg
            2VQJ34C6QiGTVpeOPOqCXCJffJ5x3JmOAcv/IkozUgEYc5wxL+SWxQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-05T19:15:10Z"
    mac: ENC[AES256_GCM,data:VPyIhoXN1BWEp2WGAxPxhPPu9vSUrd6kw32yZ8T4XfVbpWlkV0yBI0eAh4i2W+UP/3ZJ77TVNjp6Mo76C5IdX45KBj9bPHpL0nWJFmcUrrtaT0mUAVxIZGnmLARTuYdXrmGZH1uFoIrOyNVByJYRHE1RJkRff8BQYQmYIl8cpJA=,iv:JJpHH4fr/D/4MzUVbQBY9a5g9hXFZk1jroIdacgVRPo=,tag:0CGR9t5BAsQPPKd8g5vElg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
