apiVersion: v1
kind: Secret
metadata:
    name: build-server-mysql-credentials
type: Opaque
stringData:
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:zmZ1FP6tVcXdecTtFgLDeEaHiug3/rZ76lhKR30pZSI=,iv:89bZdwIAN1O9iuFLXzlm/5Wl8vdt5G0XCPxfZU3VgPs=,tag:fSq/+YL3/8qf9QMVAUtl7g==,type:str]
    MYSQL_USER: ENC[AES256_GCM,data:jsaNpGSKvTuIgpI=,iv:3BGIjAyTMOjxF1Jh0qd2PI/sHhf8KQfHUEB5ZqDzmgg=,tag:b67VSDaahlcWH7ZRHmpgGQ==,type:str]
    MYSQL_PASSWORD: ENC[AES256_GCM,data:c7StOpmGtt9ZWNjA/BlhmSPKB+ea+C/TBB8UgbOjWkA=,iv:oMx0Ugm5UOsCg4olFcsgeynP8wYfRaOS18yo0tAe9xk=,tag:zg9SEDk8cHYE9MINgKXVvg==,type:str]
sops:
    age:
        - recipient: age10p7f8sn3v2r0973s8q4664sgxh4hpt8c0tp3w83w8m0zu5rkfccqge8atx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxbDVMNmFodXFHTFY4OHRW
            dVR0aFJMUW4vQmtLdzd1MVZnaXdQUjV0a1g4ClY5Ykg0aUhzMXE5clFQdlRWUHps
            T3pwZ1BOK00zRExiRVBiTGdOU0pZTEkKLS0tIEZGVW56TXNCWnQxWWRySDBFWU90
            bis4TGIwS0NxS0t0TXFJQS80Qk1ZVW8KtcPMdOio126OLYEJ3gRlGxGVtz+FrIzR
            DvvXgh0Gzshlf8OqBpwqpFx+aJP79sr8ujBueuA/5iWiXESVIP8ogA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-05T19:15:42Z"
    mac: ENC[AES256_GCM,data:fifgumDA3AcapdbrGJrRjAcPK5tRrzsTY54RJQ/C1JqyTL4HuERBzTSD28mRiPJ2zj+RAwEOEYBRZCcbbkNLXAg0/9lB8aHeAIe0aL2M1vvkA8mfWNjMAfFf2MLinjDegUBpNH/dpt0N7fpvVCeH2Lg0R7oZHi9Kfs7i+Ks7K1E=,iv:S8E+Ci01lh5ssRRw6pgqsRAen5blwcyV3J7ZhIBn/Hk=,tag:ANfho2S5azQUBHVB+AaSMA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
