apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: build-server-mysql-data
  labels:
    recurring-job-group.longhorn.io/gameserver: enabled
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-gameserver
  resources:
    requests:
      storage: 30Gi
