apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: plugin-updater
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames: ["plugin-versions"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    resourceNames: ["build-server"]
    verbs: ["get", "patch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    resourceNames: ["plugin-updater"]
    verbs: ["get", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: plugin-updater
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: plugin-updater
subjects:
  - kind: ServiceAccount
    name: plugin-updater