apiVersion: v1
kind: Secret
metadata:
    name: livesync-bridge-config
type: Opaque
stringData:
    GIT_REPO_URL: ENC[AES256_GCM,data:ItjMX7SV3y+u2S/fA+UoDXjCP54WcODD0VfHx9eNFPR8a7fkPHTBCd057M4gRw==,iv:ceWuSHsTw7BbXV2AxbE/6sdSXEjvPTKuSdmjVdBwjOg=,tag:iAO641mfBHDKDr7EOvqhCA==,type:str]
    GITHUB_TOKEN: ENC[AES256_GCM,data:8YidFsaI+HmbKz2ZpISFP4GfFYCzf4LLYQZcGhMpDys4ygJtZ4EhygVADe1eKY8TznBov1GOXI+rr1hCSD1kOI5Kmpynmd8Xcf8lEruX2CcdJXnE6nHg6I5KECLX,iv:fMaQ43qwioLH7/7xFjegY3Y95oxpUUMHy6Dc7lMLo7g=,tag:Tb9PLqcr7AZCmVqp5l6BPg==,type:str]
    config.json: ENC[AES256_GCM,data:zmGaOi2aSBHfKptesRNEl2qLpCF9cDoZk007kMMjMEXV6cI6P4oUJkC9Hw82F6USVQuvK749FfomPnjvlTjiQSYOdGfSktYOJuT6uIIFFmcS5kHnzNrSHx0UY/fmM59iNo6vjQte9Z1ZqmmYBmqAi6/PVHYIQozANRTqrCNKgSdBVeinOIYdmw5uG2rOynahYzpH0uoAR4QiyT7JWrrfc5xwIhfLTodnDhKtZ/M9D2RbL9uZyIqpysTwITfoIFB66LT8XO7Kk3xAKOKULatCoPifnRsXX+HrJUdDgrb9iQO0R/uDziF+R4tSfpYy0JiyQox/9mByLb/lV9PpzBESHsxZTbS8Y5xUFXT0EVqHROKehZC5t4xkiASF8d/8DQE6CsVrVFwiJ4kNYXJC0q1FAEDkiESCrWh4OHsm+at1Bp1rGGTaJEBMZ6Ad1q6L4EddHaykNVWmhDsIRLbA1WnoCgZQC2KYVtsEixZNIlzjM4YLrhlHAKUnQMZdVKLcMMh665+W3QO4NqsJ76w062z+yaealen+1e4IJCntlrNdRfixbVWUwtiOq9mv0TsO7anXKPvFo/u2+rakA9gQbEm4OvnvHSa0vVFF8a6kNtLpdzFbKLrG8aSFSplZ4OJ+FeT0MJjkZ18QyHN21ok2VEXmnLoKOBd85F0pWxqvbYh1mngGIOAy1xOPATjaKfumx6xJjUlXYmPlmcf6xenXiyM26Zyh3FTnQYIs3BTQDEdTgJVxMjzGFziM4K1OWWCNUz5QF70ybqSjxqoMsififpJOV+PmsQfY3FKKQ0YCmtPZDhEacFiTiYDeF4+38aQBeYgSef4v3zmAoUt1BItyAJMqgM0m8qibqVikFvZ4zNJ+AHJ1X7Z2Yxfyvagf8pQXZkhdNtlfY3c5R7LkdSQjMHpmjKkB2CPXdIp8BY7+kOPnCCKH7IK01cNccCqR4r8wS9MiiU0Or3HSPtAXs0XxxsKKeK4oJz4dq+Lob0SMZNvlvWMUukFJq2mRyoFhPj3v1wunnnxSgWmLrqNWaTlGLZtJvDzhscQCbjHn/zQy6GveeckkL3quclB2tfLQsCPpYhbYy/boZaoJaol5lrQO6IJl,iv:vVp7SvRLx2z5RfKVUxsVc2wUgiVfNK3MhQjZTFd7Fgc=,tag:QP6ZDw6Jhs7BY0TXjh4mVw==,type:str]
sops:
    age:
        - recipient: age10p7f8sn3v2r0973s8q4664sgxh4hpt8c0tp3w83w8m0zu5rkfccqge8atx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoenNwYmlCWk0rK2I5RUI3
            dW4yeXVrV3lVODNCN3VIWVRxYlhxQTJUUUVVCmtUSFBaODRUby84ZGJCMTAralFU
            TTd2dThEMzdqUS9kcFFYN1NpRGpuL1kKLS0tIGovM2ZiM2hncjdiUnBkakREa3pG
            a0ZueEFjR2ZwQWhrUlBGbTMxMDdaeGcKZ02QnZCDHVKWpU6PtL+8qxfGpcXeNRaC
            eBH81nW/dSHU/F2KWOABjsTN78MS9lbW8yqdk0W2HFYN6HkKbRjWsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-01T06:43:56Z"
    mac: ENC[AES256_GCM,data:zzbD9Ou1CBENnjfwolV8M0we+2mVkY+oNSWh5/BwfMClYcF8mJkvcrWrbK2WgwbG+1NPtf3F1R5io9wYJtaoKmZ6yCNq2tyeLgQSe0pjvDeJ5M8emuWqKrOjv3rSthMJ0+BZyHmInhAw3KwuQLut2FNnVintIdZnFy/T1ZP5RX8=,iv:LVfDev2Vzdf1iB4Nmqwghr4DvCoXRAnoAO/qNSblTH4=,tag:II+iJQXC/ZaI4mdDKQLsTQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
