apiVersion: v1
kind: Secret
metadata:
    name: livesync-bridge-config
type: Opaque
stringData:
    GIT_REPO_URL: ENC[AES256_GCM,data:ItjMX7SV3y+u2S/fA+UoDXjCP54WcODD0VfHx9eNFPR8a7fkPHTBCd057M4gRw==,iv:ceWuSHsTw7BbXV2AxbE/6sdSXEjvPTKuSdmjVdBwjOg=,tag:iAO641mfBHDKDr7EOvqhCA==,type:str]
    GITHUB_TOKEN: ENC[AES256_GCM,data:8YidFsaI+HmbKz2ZpISFP4GfFYCzf4LLYQZcGhMpDys4ygJtZ4EhygVADe1eKY8TznBov1GOXI+rr1hCSD1kOI5Kmpynmd8Xcf8lEruX2CcdJXnE6nHg6I5KECLX,iv:fMaQ43qwioLH7/7xFjegY3Y95oxpUUMHy6Dc7lMLo7g=,tag:Tb9PLqcr7AZCmVqp5l6BPg==,type:str]
    config.json: ENC[AES256_GCM,data:aogiz5DJvNrvYm6PqaY1BxyROFYKB15mshnjlmYD0r5VJps/80gQYMi7pcKpXHHehKO7m9gESaN7RQ7g/jD3x3GjypCp+f4Ib4Vjxp0JWXnDhA8mqjZq5ioTtLBLBDrFx5tgHJBHK55li4AYW4t7EnClYW75dhnBF8C7i0ZPbKdPswmWj6Vkpm8ux5vTll77b1GT8WkG7GKEhr626sh/bjIXWqRMQSNtqq7Jo2Bh2phXZ6FTU281nmGNid+3uJ5zGL3vyLpoZJY9JuI+7XM5fUoxnpN85jvHx3hJwonrFMFoiQ8qi2l5W/s8s+3XPWB2h+3E/KNT7PdoHaZn4gomwIC8d2+u97/7xo24LlCyaYo2p0kIOvmHygzejXcPLRsq/IXafi3an5oinrgDsA4ve0hKURLVfzKFZytISEJCJOEbfGP1xP2MvckrRVhMbndSxShPiZZpQq+xFzO4C8mFwGPJPPFqwK5xrZleEvjKb7jbbWuWe1X+s0VJFajWc7AxQV7EWMhB6OeKPaJAyKzLnP592wWYO3/KU//KIGG2iZPebb4k59BOawZGs+kMvBZcrklFkH092C55uKf/eseJ69Wb3OcSfQdX7CgNiiYcgFO9Ki3hDKzdYGsaYuP5uamx8Xo/Y4WFic9tRWS/TzOhSiYbIqsMl/9JeHhHJJlU9TlYFjwYBNmKOxrZGcJ7HNVDXekac4enxiT6hnrkuB891FcXrqD1xOuK/LJs+cmMtzS6gynOAYdlTBF9tqwJ4Rf0+O/GzHDBbHlOGje5elv6FxWB2weR1LjbehWb5qWAG0M/luEPP/C0DZ5kNNynKJEJSlzykXNiIrtH59RpXVIejMoNURrMrs3peREILNXnCV3Uw7CToiafc5L3+YmDh0TytCX5rG3xtmn8c54Du6Besg4K0OYiiD0tHceXNwcttu304C6jR2RXbh1ehT3AUb+bRC0T++UY2sRfn2GGVL2xEdsdB/w58ySFkDsCKEbimZK7fEksDSSA/wQbxeSq4o4nPL99a8dmML1i07x+eibpNsbAi8k6iW8D/rVAXnKdAcpF/XSrasYCqm+1FFoKJe1E0ASj9udt8YrrtLvnWo4=,iv:HB9DneGJKhAoo2EqSp1vHOebpzZCYN905OBQSKKu1lo=,tag:yUWrMRzZ77KhBcJnN7gwEQ==,type:str]
sops:
    age:
        - recipient: age10p7f8sn3v2r0973s8q4664sgxh4hpt8c0tp3w83w8m0zu5rkfccqge8atx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoenNwYmlCWk0rK2I5RUI3
            dW4yeXVrV3lVODNCN3VIWVRxYlhxQTJUUUVVCmtUSFBaODRUby84ZGJCMTAralFU
            TTd2dThEMzdqUS9kcFFYN1NpRGpuL1kKLS0tIGovM2ZiM2hncjdiUnBkakREa3pG
            a0ZueEFjR2ZwQWhrUlBGbTMxMDdaeGcKZ02QnZCDHVKWpU6PtL+8qxfGpcXeNRaC
            eBH81nW/dSHU/F2KWOABjsTN78MS9lbW8yqdk0W2HFYN6HkKbRjWsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-01T05:50:48Z"
    mac: ENC[AES256_GCM,data:sYYNxjnaN7sFu9OYmYdLpmOeaSAhvjBrrg0bReO3APIGfmjz+igPK3Jih6rlvwMFVW2VdyEh+t3VL7ue234t2tw9uuSDWYDrJDsGtYgFAvyHJ9XYFmo2X/xRxByjt29COIutcL+C/7PoKqL8NgjDtknZyq+mZeWiOoR/DLhQiXQ=,iv:c5yrhl8PRVfVlu4u1TZOP8GiRN+tGkvjcbRgiC0mw/E=,tag:M/9RNh6TIRfJUQI9lanBaQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
