apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-credentials
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:5HZfvIo=,iv:fSVKOFd/Uw5F8T3EGDp0grvM9i8tn2zpIbRh06NzxSg=,tag:3SxqPGqrTBp4fatXcsyF0w==,type:str]
    admin-password: ENC[AES256_GCM,data:x3dtt60ZI2NlHXbbuNWyOvC0Zm4=,iv:V1p59l4UswkgGyneLYXJzCzcMZsdQoCK9V4F7A8+xgM=,tag:lHLutONoOonp+NN6NPTS/g==,type:str]
sops:
    age:
        - recipient: age10p7f8sn3v2r0973s8q4664sgxh4hpt8c0tp3w83w8m0zu5rkfccqge8atx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArTEx5VGd3OWhqaEIyTkw1
            b1FlVVBEUW9YdXlJZzNzWDV6VDZqL3JQcWs0ClpIVis3TjBOdE4xbXg4NUU0TWpB
            UEFodFN0N0NSWVhCSHR1RER0R2tHdFUKLS0tIHd1NDRpMnFtTkFwT1hYd1p4MEFJ
            alJna1dTSU10ekdpaHU0OXhSVFBBNGcKMBVLpIQdp5EojunoeQn3afgjhjG4vKEk
            D/rB92iRpqnrfvH9zSE+4M6R57x1d7ZlOG9j5ygxKfCD/fxkLFg7+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-01T04:54:27Z"
    mac: ENC[AES256_GCM,data:YJWXeUi8wlgOVYpi0DGAWEqiz3wRLiWdGQadHjdfe2Kz+J32TXMsDvXpcENvVBSQTcU+aygu3dqnRq3vgUB+K+l+9eYcxGDIPSceKAQFPy/R2NMwjzTxB3/POf6QdFLrEBy6jBqIaWirfF8w6khais+jhx+hv29fcFCJiH/X/tY=,iv:KIP1QPDUPhW6LBlk5xLTqDgYYOO03cs4Qk8PCXpTg4M=,tag:8EQGMUqCzG6Htmm5wmCXiQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
