apiVersion: v1
kind: Secret
metadata:
    name: lepinoid-auth
type: Opaque
stringData:
    GITHUB_TOKEN: ENC[AES256_GCM,data:5JBAjEcR7EEupuJDa6KP7sTz5O0e/zCaDOLN6Vk3O5k1joFEVAl5zd2jBKycIRj39QuZB8NmJosO6/TBpqy7YDLLghdvjEmAYLNdjHcCCj2LV3LRzUuNuCUEvRsA,iv:n4yxNp8BeMWTkKDE9e7G+qlU8E2C6YSS/h20xKaT4C4=,tag:gDjZqY2orLFJzqhNSoIKzg==,type:str]
sops:
    age:
        - recipient: age10p7f8sn3v2r0973s8q4664sgxh4hpt8c0tp3w83w8m0zu5rkfccqge8atx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpK3hvaEFDM1JyaUQwbmVI
            MVpGaHFLMmRESWwyQWhaQ2ZhbTEwNDVGSEJJCnA4QVVwMWhOb25ibUtWeDg2R0I5
            ZnJEUlNFSWZxSHN3Z0pGQS8vR1ZFbzgKLS0tIGhmNWcrenE3TG9zVndpelV0bUR0
            RW1aOUhhY2VBM2lVbWxsWlY2eGJJUmMKec1+sYBbAVH/dg5aZIw2ol56k2HGO3Fh
            GiEP9RjBf07mpIGtDXTiwCod/AyL5hUU1xkmobcNOoN6cHzhZN4D3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-01T04:44:26Z"
    mac: ENC[AES256_GCM,data:15ki7GqUQDhmCQTyHTgX7kd7DO//eyt0EWYk3jrzr/W77r/QAtJhQU0WWxw5LBDRfRAuaKA0WDYpkwkICpk195XFXtV78smR0mLZl1bqtKjd9n/WKtZDegW8Vuyq/b1Slcgsx6V3AMRr0UfABRHflc2P0s2HhxhaNjt9B9m6rHo=,iv:mcixbRznwjMyduCjd1Z/XWcmxcaDOheXrG+DwLkuzWw=,tag:2cdlS8azGFFSea2algQlPw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
