apiVersion: v1
kind: Secret
metadata:
    name: lepinoid-db-credentials
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:KLgcYQ==,iv:Uab+dW+ynsghTZViM3+MOppvTtF4bAVomLXfwj3zQtM=,tag:+8rtQuTkuLPNfzQY2tmWMA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:+T6jMQ4bemQEoRYu,iv:FiI8/sRZpApnUbK1YQRtzvM97d30d4s9InPitIXvX/E=,tag:RF6Wbq7Gcu5o7cFwByPF1A==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:OmiNSFCqnAE=,iv:/DpzL+pHMponR6IqE5O8grrTZfN9hg3omoWKWzEoHcA=,tag:BGgpiddXXjT1Bkypf1fJkg==,type:str]
sops:
    age:
        - recipient: age10p7f8sn3v2r0973s8q4664sgxh4hpt8c0tp3w83w8m0zu5rkfccqge8atx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtV1BkK2kyOWlwUFdUaFlU
            U3VxV0hXNEpiY3V0d24xQjl2Yy95aHpCZ25VCmUzVkJnR2JtSEtnYkl2NmdUTkQ2
            aFliY0E2WGx1WnlYN1B4Y2wzWlVCOXMKLS0tIHZYRHR2SWRUaTNRSFU5cmJXeldI
            bUIvb1BBSzZNNFdYdDNKdHc0VWFWOEEKvetoZV+DvdwtWgu9TMsYDo/uykXU2VRH
            R/WuoTrh4DORrwpC/LrFh9jPdB4X35J8G1IVhvnmseq4WtPy28sz4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-15T11:16:03Z"
    mac: ENC[AES256_GCM,data:q7qNZppXQuvmf44SZcMo9tNBgBV1+aBxMVKT5k5g9WBx88R/7gdBcO+vS1X4TDIzw5CLvwhPUbkb5fb3lEHU+y/B9Mt1UgKXRQilSq1J72o7WzcBQI5URiOx7S+m7PMSpxeq+iguI/jflB2Oo11wCcKxTGKzkqwtMZB29paGv4Q=,iv:DjPyyieKms+oiPkuTlaBHfxKOFdoHhpKpNalCG40/UQ=,tag:Jxl03+eU8/neqpef/wCVUw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
