apiVersion: v1
kind: Secret
metadata:
    name: lepinoid-db-credentials
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:vVMp60mgka0=,iv:OB96l4Z+c8QmpP6E0iWwMyHlHqh1aUcEoR0t6aDzhpo=,tag:eHj4E0Is1dTLJ2nrbl7h9Q==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:+T6jMQ4bemQEoRYu,iv:FiI8/sRZpApnUbK1YQRtzvM97d30d4s9InPitIXvX/E=,tag:RF6Wbq7Gcu5o7cFwByPF1A==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:OmiNSFCqnAE=,iv:/DpzL+pHMponR6IqE5O8grrTZfN9hg3omoWKWzEoHcA=,tag:BGgpiddXXjT1Bkypf1fJkg==,type:str]
sops:
    age:
        - recipient: age10p7f8sn3v2r0973s8q4664sgxh4hpt8c0tp3w83w8m0zu5rkfccqge8atx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtV1BkK2kyOWlwUFdUaFlU
            U3VxV0hXNEpiY3V0d24xQjl2Yy95aHpCZ25VCmUzVkJnR2JtSEtnYkl2NmdUTkQ2
            aFliY0E2WGx1WnlYN1B4Y2wzWlVCOXMKLS0tIHZYRHR2SWRUaTNRSFU5cmJXeldI
            bUIvb1BBSzZNNFdYdDNKdHc0VWFWOEEKvetoZV+DvdwtWgu9TMsYDo/uykXU2VRH
            R/WuoTrh4DORrwpC/LrFh9jPdB4X35J8G1IVhvnmseq4WtPy28sz4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-28T13:50:10Z"
    mac: ENC[AES256_GCM,data:aKFUe1qjfwNsDY3wlbN1ZS/0kpWcBD+Deb/Tqf92z7hk6F30vW0kPRHKWzrux0Bej3+HRhpOZ6fwkGvRh+hG+k09HytUXnuPVexIEYHsVhMqBLMT7AVL7dQNyEOp4S9h+JIlgE5YPlz5vz5FRkRPl8UwHSuUze8tca2SV0EJKp4=,iv:jBTjt58s0ZATEfNFVmBib0Jz22MF1wbPeO1+kY/yNsE=,tag:bQJx8oniKqpG73Fves0cwQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
