apiVersion: v1
kind: Secret
metadata:
    name: ghcr-pull-secret
type: kubernetes.io/docker-registry
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:+cS+Pt3jikdPGdaGFQXRX5Xp28Yr9mE+uZVkI3X3rowOvic+j0gVBjr7RhnvGkYR9ASu8iXBEudHbHzwzc5/H5T3+ygBE6Yk59yN06bVxyddJSIu8YkCWTL1yZB73RlcT2o=,iv:aX6Z0xtEe5yXODLQZJQLrGBGOUmvf5TyN5OTxbuvlk0=,tag:mQ/IGVwEk3k4xTzs1TtYsw==,type:str]
sops:
    age:
        - recipient: age10p7f8sn3v2r0973s8q4664sgxh4hpt8c0tp3w83w8m0zu5rkfccqge8atx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2bTJieWIzRW5DdDdNUWlO
            NFpFMy9uZ3R5Z1NaY0xtd0FrWERvYlNTNW5jCng2VktFRHlPU0FSYisvODlmYkpO
            NXcwNUNzZUJ3dmpmK29Jd0RQZTBYMVEKLS0tIFlHZGpNRTZOZEV4NHZPbTNYYnZQ
            R2ZRUWVhQ1pqemM0bmVQSE5mM1VMMkEKHnkZkb9Ay7mUBBmC2u+CApW224BV/Ndi
            Cr6OJ0zECJI37CSNj5XKH655jVebiigvZwhPrKzLt235tqTFIsfVxQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-15T11:46:41Z"
    mac: ENC[AES256_GCM,data:OLRyGijWicqPXGsCbijEpnS2OrLbx1R9j9M8be0YeGOgIp5kzAQZBd0MzoG7JalDBkqHElbCpsKBaX5uQtas06u/Htezxfoae9jL07ppcEbeqNQCxrq579qhqKcrq4EXJGeJpcfuQQj3hYs0JFZrTlHTokP358DzCzTO8JnnkRY=,iv:9DPVZ8vot11LKk8dM9gO5fg20XDvQn+L4jtqSqiK+Bw=,tag:EnouuHY+vKpAHyAbmq4zQw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
