apiVersion: v1
kind: Secret
metadata:
    name: ghcr-pull-secret
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:voiHN8QzzLANSkYNVwg856u78ic5/w0s4WzCCdckCxFOEiQoFhgmiMfTWpNSdmUjRQk3Dfr/JbOHHA2Kkvb4q/u8c/xgE3/Rz2FLgxvk0keeLZ9eqmStVr1CACf77SsRrrOEcr2AkZhRxKWITmkk3SkjIrTaJcyBAbzmhA2lOyPGcMRXsxwaYf79A6623dG1mHqXovXkqCKsMamKA6l6COdMmQj5xwKGzFAB4g==,iv:gFZCKwPPysGnTKdy/rEgcEzZByOxa69+rW+WoB+PexY=,tag:f+zK/R/8ILOvl5CMqdl9og==,type:str]
sops:
    age:
        - recipient: age10p7f8sn3v2r0973s8q4664sgxh4hpt8c0tp3w83w8m0zu5rkfccqge8atx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKQWNDQ1pGZTUwZktSbC9Q
            bituZExpc2tYTDhtSTFxbmhlQ1kxUEIyTUVZCnI3emlRV3p0ZGZqWEY5N0N6ZzJL
            VWdVS0x6N0hFaVJzRkdFR2REbEVMczgKLS0tIHpUanFOSVJHQUgyTjlYNXpxNHow
            Vit6eWVzV1FzQmw0SDZGc2Jna2lLaHcKKvrs+NjNJkQD6jVFYIksRkNDpHlpNGZB
            cEpe2QZS1PdoyHFtCIJJKkmBdZ1BfCbzeZ0T6wnP2zMlfDQjUtOGWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-15T12:09:57Z"
    mac: ENC[AES256_GCM,data:k0uo/mVi8Ob8CfLKdJ/0ASGisAfCAxpmyEGcwn+UMILEQTejXLp+4uY+6yLjxckhoUIlxQI2h2WXz65jK1aMi5ZAz5al3wsVKFiDVzOhqGt4ZkwBDi7sWwPzRketrBoZ+XcVAhkPKfA30hQLIbpBI05NCtENMejNGXB2X7VPbmU=,iv:j3xy9YrKxKn+vB1fJ14HLbwh2oq9pOKl2g70NKxjPpc=,tag:HflTrahRNUKaZvxZhGmiNg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
