apiVersion: v1
kind: Secret
metadata:
    name: ghcr-pull-secret
type: kubernetes.io/docker-registry
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:qXuI4xDms4oXBIwBvou24tpjwCNYVZ/N/MY7VWRGhzHT7EmwSqkWY5Bugy6YUogqCnW3SMTNIxjIEb+YFOmvUAWDC9Iu3OQ2dt3WcNl8SlynB4S76wbCgReeta3uK5WESug=,iv:svVLJk1MDMrf3C3gw2uEadhQTGPqfyNFZ0+aRPNw/JM=,tag:9j8a1RfPCma4V8pk5UdjGA==,type:str]
sops:
    age:
        - recipient: age10p7f8sn3v2r0973s8q4664sgxh4hpt8c0tp3w83w8m0zu5rkfccqge8atx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2bTJieWIzRW5DdDdNUWlO
            NFpFMy9uZ3R5Z1NaY0xtd0FrWERvYlNTNW5jCng2VktFRHlPU0FSYisvODlmYkpO
            NXcwNUNzZUJ3dmpmK29Jd0RQZTBYMVEKLS0tIFlHZGpNRTZOZEV4NHZPbTNYYnZQ
            R2ZRUWVhQ1pqemM0bmVQSE5mM1VMMkEKHnkZkb9Ay7mUBBmC2u+CApW224BV/Ndi
            Cr6OJ0zECJI37CSNj5XKH655jVebiigvZwhPrKzLt235tqTFIsfVxQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-15T12:05:43Z"
    mac: ENC[AES256_GCM,data:uMxiH1xhYatUF1h68GpJvvfubhMOfoAq3h1B5TgYWan1M2iO9flJV2LQr5GMmPsvVpe0Nx0UCDCm9SmsA/vGGUiIWv/WTC7FUK74tO/SiIA1DgY4iuNJnQnOfSEMIrNVvo4Q0+RFf4Q45H3DuAR2BJH0bOQbdTWtxCmIzy7ympY=,iv:cd9I2JOJgRIm3HQz3qefk2xeJP2H14g1E6sEltH46K8=,tag:U0rbUMN4CMDzmtzPpjnLvA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
