apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-tunnel-token
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:0wWbppAw+KltF2UHj5dH3xPQNg9vHfSOT4b/q/XAfa+98kNrr6iY3nwYIuY1wWMaZOJ3GUk0JB6bdBdDDs/dS3Le1pBJpSlPETBwD7hm3xixscfpSSvTedvOrqIhAuL9k8MRNNsuSEXhn3z4Gmzd5KFWml5+0AHUNc+E9IOnU28p3B6wsVBZhHdOfosKdksXIJPTumnNzjN1UR7kQYZozerbOIkfZk66TrU3IVw9jxktMsWelOxMtQ==,iv:NGwp+2TPwxTQ6Nbkd5TUhnZabm5P85WsLF0+YPuC1i8=,tag:bM+BqXOXDKPL+ndJ3HNE6w==,type:str]
sops:
    age:
        - recipient: age10p7f8sn3v2r0973s8q4664sgxh4hpt8c0tp3w83w8m0zu5rkfccqge8atx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRVmhiZEg2Q2NUaFhFTFFu
            dGNsdHdjdFNjV1ZweEJqYVJ0NGdnVjFjUHpnCk4rQXJKbHIwUmRPTndOaGVIMENF
            V2s2Z2YrS29yZ0tBcmpCNjlSVXkrb0kKLS0tIEh5WmVFQk14RmFhOGVqRkhXQ2U3
            TmZNMVo5alVkT2pZdmpscnZQczdUblEKAiMQYvyGQRBHW4+wbvyp2WU0ljDT530y
            PlsOU80oeEjlEk0sBiC99fS8QgFWNNyex6OSdkqOOsYOjps50+dqXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T16:14:56Z"
    mac: ENC[AES256_GCM,data:yY9C/HvkB67taVMjCT+mSY8OSkm3h8RzY54WyuvpuzBkg/KxIWza3PW3adWDKpdyEAX8YyVkF27lbgLaZLsFi5MKSM/MTQi4f96C7nHcnFXVv5sfI0EbkGecWikh86fUvRc9EgMclwtEZBLFCDvI82/GuHo8MqwiHE0IwV2YXyQ=,iv:+E0Umblljo5EkXUCVBjg0+aqI/7PNm83MvijQ2h70yo=,tag:4WNCsGlG4cb9b3jlqwWgBg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
