apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-tunnel-token
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:pzmoYaZlN6BQ9welbtme3bj9rusurimjYOwqM1RGATNbB90X3Uo8ox07WDAhNYlM0SBPvLUPIDRKmVK9gDVWgwvu4C3/nyZolz9ik4VCvxg0cfuPTWXTAOvGaZxF784vyuHNCFk5lwnN1MShcxGKEOfWBE+n3C8fh6jlTrMVirJGHaX3KcrobPpgOKTpdFhccX7xLXbWQ7lq4wtKQoo7UzmENSy98TAs0HJbKBsaju6tDKpr3hNgw+KXRqDy4Wy/1qSUeonwtyViDjGF+RbuIaUkgk/+A0Ghv0V5Yo+c33dlWJAIdzZRFc5z10ZJTvSl,iv:5273CPjgMGyz32cB3G4S1Z/kkVSuDIrqnpIrTfODVuA=,tag:bEKgQgZ/z/db+3Dmk45v2g==,type:str]
sops:
    age:
        - recipient: age10p7f8sn3v2r0973s8q4664sgxh4hpt8c0tp3w83w8m0zu5rkfccqge8atx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRVmhiZEg2Q2NUaFhFTFFu
            dGNsdHdjdFNjV1ZweEJqYVJ0NGdnVjFjUHpnCk4rQXJKbHIwUmRPTndOaGVIMENF
            V2s2Z2YrS29yZ0tBcmpCNjlSVXkrb0kKLS0tIEh5WmVFQk14RmFhOGVqRkhXQ2U3
            TmZNMVo5alVkT2pZdmpscnZQczdUblEKAiMQYvyGQRBHW4+wbvyp2WU0ljDT530y
            PlsOU80oeEjlEk0sBiC99fS8QgFWNNyex6OSdkqOOsYOjps50+dqXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-29T01:47:23Z"
    mac: ENC[AES256_GCM,data:MS7tYGCDGSxG/xTjXoB3BTfsnjE1AbJeB+FayKg7WxDSfqOi1N2KbUn9Ozua963vb88nwixWNR/svBkf0ss6+qAVeVjiJREPISxRdGDHQx7IhlEzf0+PvtfA23R9bYmoTwVClIQhowbCqj1ABrXVufIN/8/96fPtsfxhRsI5iZA=,iv:I/39iy9ZPnzZE8HKFNakcQzYn0f5uCpBLFkFN5en6zo=,tag:G5CeXDkd5CcINBax2Y3X6Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
