apiVersion: v1
kind: Secret
metadata:
    name: couchdb-credentials
type: Opaque
stringData:
    COUCHDB_USER: ENC[AES256_GCM,data:BWNYqgWL38zI,iv:OmXrqat7Vn1y1r2tv4gez3fRLUdN6DsEle81Lm89e6E=,tag:2DpNmaU41W132+Uejtc/ag==,type:str]
    COUCHDB_PASSWORD: ENC[AES256_GCM,data:bSyHujOwtZqc1miqWDL4umdBaHXwIIkXZQ==,iv:vH+ayscg3op2pjriw2tWSd/Bjb6OmushY+vMRKYgdI4=,tag:beE56VDu5o5LpHpFuuSsUQ==,type:str]
sops:
    age:
        - recipient: age10p7f8sn3v2r0973s8q4664sgxh4hpt8c0tp3w83w8m0zu5rkfccqge8atx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXVnB3NlhRNlhpcUlZNlhj
            MENXVVBmTEhKVUhMYW4zZDVMNGRaZFYvblFRClZOQnBNeWZNa3JrbXBYOVhpeG1D
            Mjl0c05IalZHZDVwRG5JaVFhc08wKzAKLS0tIEJ5NEs4QW4yTHVKUWhNQkc4Ni91
            RUp6TVZsd0pvblNVME5sQmV4SUx0akUKIyZWLdNaxT9EDRzdEulGCO87/XtngvTX
            7dP4jO3rfx5b5u/r5P3eshLtrl8DbycU4FhCeK76EHsue84SYqARUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-01T05:41:23Z"
    mac: ENC[AES256_GCM,data:30Ln3m6kqtP61InTtOL9q9p61uyAu8pm7UUlD+XcrmcVAYWRxkJFkXiEhQh4hFV9LxTsl2DY5N4J/EAmyPYkEULwyUcx+Q2UHIE6f3Z9O4QsGLxkQFXgI+/fFwks3HMiK3goaZnZzwS5vy8fczXYDyx/nzdxw1zg6e16SPSPfTk=,iv:cpn+Qlk4xO8EfsO5SJKw4m78mKfSKtjQ47UFYNN5gBY=,tag:gIUBFw7eCkZvZww+WwxflQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
